Uicleanup
venkatapathy/ocr-editor pull request #20
Opened 2022-02-01 09:25 UTC by harrionparrix

Change Name from Sandhi to OCR-Editor

2022-02-01 09:56 UTC, venkatapathy requested changes

2022-02-01 09:56 UTC, venkatapathy commented on README.md
> +3. Now copy this port number and add to his address to “mongodb://localhost:[Port Number]/OCR-Editor-books”, without the brackets. Now go to server/config/appconfig.py and paste this address after ‘h
it should be just ocr-editor

2022-02-01 09:56 UTC, venkatapathy commented on pycodes/pdf_to_txt_tesseract_ocr.py
> -    "Give path to the folder where pdfs. Enter for default option: [~/Documents/ocr/sandhi/input_books]"
can we make [~/Documents/ocr/sandhi/input_books] into [~/Documents/ocr/sandhi/input_books]? @harrionparrix

2022-02-01 11:25 UTC, harrionparrix reviewed
ocr-editor in place of ocr-editor-books

2022-02-03 01:26 UTC, venkatapathy requested changes
This should not be pushed to the master yet. I have it in the branch cleanup and uicleanup. Remove this as part of this pull request, please.

2022-02-08 13:41 UTC, venkatapathy requested changes
@harrionparrix please check my review comments and make appropriate changes

2022-02-08 13:41 UTC, venkatapathy commented on frontend/client/src/components/PageView/PageView.css
> +.background{
the UI changes can be skipped in this pull request

2022-02-08 13:41 UTC, venkatapathy commented on frontend/client/src/components/PageView/PageView.tsx
>  import ToolBar from "./ToolBar";
Again UI changes can be skipped. sandhi to OCR-editor changes alone can be added

2022-12-29 10:13 UTC, closed without merging